language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ellsclytn/multi-test -f./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ellsclytn/multi-test npm test

after_success:
  - docker build -t ellsclytn/multi-client ./client
  - docker build -t ellsclytn/multi-nginx ./nginx
  - docker build -t ellsclytn/multi-server ./server
  - docker build -t ellsclytn/multi-worker ./worker
  # Log in to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to Docker Hub
  - docker push ellsclytn/multi-client
  - docker push ellsclytn/multi-nginx
  - docker push ellsclytn/multi-server
  - docker push ellsclytn/multi-worker

access_key_id:
  secure: $AWS_ACCESS_KEY

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-us-east-1-519286424990"
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  access_secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
